language: rust
sudo: false
rust:
  - nightly
  - beta
  - stable
script:
  - if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then cargo test --features no_std; else ! cargo test --features no_std; fi
  - if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then cargo test --features const_fn; else ! cargo test --features const_fn; fi
  - if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then cargo test --features 'const_fn no_std'; else ! cargo test --features 'const_fn no_std'; fi
  - cargo test
